### PR TITLE
fix: update scan run without reading first

### LINKED ISSUE #620: [Bug] Remove unused data from the queue message
## Describe the bug
- In the scan request sender, we add id, url and priority to the queued message.
- But actually we only need the id, we have to read the document and for that the id is enough.
- The url and the priority aren't used anywhere.
- It'd be better if we remove them.

Also try to use merge for the document instead of reading then updating

Maybe something like 

public createPartitionKeyForDocument(documentType: ItemType, documentId: string) to get PK so id & doc type should be enough 

publicasync mergeOrWriteDocument<T extends CosmosDocument>(document: T, partitionKey?: string) then can handle client side merge for now

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service

### PR DESCRIPTION
**Pull request by pownkel**
#### Description of changes

- Remove unused priority field from OnDemandScanRequestMessage
- Add batchRequestId to OnDemandScanRequestMessage
- Refactor updateScanRuns to accept a partial document (with only id required)
- Refactor runner to update the scan run document without first reading it

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #620 
- [x] Added relevant unit test for your changes. (`yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] Ran precheckin (`yarn precheckin`)

### CODE REVIEW

File: packages/storage-documents/src/on-demand-scan-request-message.ts [hunk 1]
```diff
@@ -3,6 +3,6 @@
 
 export interface OnDemandScanRequestMessage {
     id: string;
+    batchRequestId: string;
```
Comment (devaradhanm) [inline packages/storage-documents/src/on-demand-scan-request-message.ts]: why are we adding batchRequestId?

File: packages/storage-documents/src/on-demand-page-scan-result.ts [hunk 2]
```diff
@@ -71,3 +71,7 @@ export interface OnDemandPageScanRunResult {
     pageTitle?: string;
     pageResponseCode?: number;
 }
+
+export interface PartialOnDemandPageScanResult extends Partial<OnDemandPageScanResult> {
+    id: string;
```
Comment (devaradhanm) [inline packages/storage-documents/src/on-demand-page-scan-result.ts]: also add partitionKey

Comment (devaradhanm) [reply packages/storage-documents/src/on-demand-page-scan-result.ts]: these two should be mandatory fields to avoid cross partition query

File: packages/storage-documents/src/on-demand-scan-request-message.ts (hunk 1 above)
Comment (pownkel) [reply packages/storage-documents/src/on-demand-scan-request-message.ts]: Originally we got batchRequestId from reading the scan run, which we aren't doing anymore

File: packages/storage-documents/src/on-demand-page-scan-result.ts (hunk 2 above)
Comment (pownkel) [reply packages/storage-documents/src/on-demand-page-scan-result.ts]: We can get the partitionKey using the id and itemType, so I don't think we need to require it here

File: packages/storage-documents/src/on-demand-page-scan-result.ts [hunk 3]
```diff
@@ -71,3 +71,7 @@ export interface OnDemandPageScanRunResult {
     pageTitle?: string;
     pageResponseCode?: number;
 }
+
+export interface PartialOnDemandPageScanResult extends Partial<OnDemandPageScanResult> {
```
Comment (lamaks) [inline packages/storage-documents/src/on-demand-page-scan-result.ts]: likely this interface does not require any members at all since it should provide all `OnDemandPageScanResult` members per `Partial` target functionality

File: packages/service-library/src/data-providers/on-demand-page-scan-run-result-provider.ts [hunk 4]
```diff
@@ -45,10 +45,11 @@ export class OnDemandPageScanRunResultProvider {
         return flatMap(response);
     }
 
-    public async updateScanRun(pageScanResult: OnDemandPageScanResult): Promise<OnDemandPageScanResult> {
-        this.setSystemProperties(pageScanResult);
+    public async updateScanRun(pageScanResult: PartialOnDemandPageScanResult): Promise<OnDemandPageScanResult> {
+        const storableResult = pageScanResult as OnDemandPageScanResult;
```
Comment (lamaks) [inline packages/service-library/src/data-providers/on-demand-page-scan-run-result-provider.ts]: may be `persistedResult`

File: packages/storage-documents/src/on-demand-page-scan-result.ts (hunk 3 above)
Comment (pownkel) [reply packages/storage-documents/src/on-demand-page-scan-result.ts]: I think we do need to require id, since we need it to get the partitionKey and update the document

File: packages/web-api-scan-runner/src/runner/runner.ts [hunk 5]
```diff
@@ -37,25 +37,31 @@ export class Runner {
...
-        pageScanResult = await this.onDemandPageScanRunResultProvider.readScanRun(scanMetadata.id);
-        this.logger.setCustomProperties({ scanId: scanMetadata.id, batchRequestId: pageScanResult.batchRequestId });
+        this.logger.setCustomProperties({ scanId: scanMetadata.id, batchRequestId: scanMetadata.batchRequestId });
 
         this.logger.trackEvent('ScanTaskStarted', undefined, { scanWaitTime: (scanStartedTimestamp - scanSubmittedTimestamp) / 1000 });
 
         this.logger.logInfo(`Updating page scan run result state to running.`);
-        pageScanResult = this.resetPageScanResultState(pageScanResult);
-        pageScanResult = await this.onDemandPageScanRunResultProvider.updateScanRun(pageScanResult);
+        const pageScanResult: PartialOnDemandPageScanResult = {
```
Comment (lamaks) [inline packages/web-api-scan-runner/src/runner/runner.ts]: probably we do not need that strong `PartialOnDemandPageScanResult` type, having `Partial<OnDemandPageScanResult>` on `onDemandPageScanRunResultProvider.updateScanRun()` definition will suffice

File: packages/storage-documents/src/on-demand-page-scan-result.ts (hunk 3 above)
Comment (lamaks) [reply packages/storage-documents/src/on-demand-page-scan-result.ts]: As per other comment I'll drop this type. `Partial<>` as func param type should let use `OnDemandPageScanResult` arbitrary members

File: packages/storage-documents/src/on-demand-scan-request-message.ts (hunk 1 above)
Comment (devaradhanm) [reply packages/storage-documents/src/on-demand-scan-request-message.ts]: we have deprecated batch calls. so we dont need this anymore.

File: packages/storage-documents/src/on-demand-page-scan-result.ts (hunk 2 above)
Comment (devaradhanm) [reply packages/storage-documents/src/on-demand-page-scan-result.ts]: you need to validate just querying for id doesnt result in cross partition query

File: packages/web-api-scan-runner/src/runner/runner.ts [hunk 6]
```diff
@@ -37,25 +37,31 @@ export class Runner {
...
+        this.logger.setCustomProperties({ scanId: scanMetadata.id });
 
         this.logger.trackEvent('ScanTaskStarted', undefined, { scanWaitTime: (scanStartedTimestamp - scanSubmittedTimestamp) / 1000 });
 
         this.logger.logInfo(`Updating page scan run result state to running.`);
-        pageScanResult = this.resetPageScanResultState(pageScanResult);
-        pageScanResult = await this.onDemandPageScanRunResultProvider.updateScanRun(pageScanResult);
+        const pageScanResult: Partial<OnDemandPageScanResult> = {
+            id: scanMetadata.id,
+            run: {
```
Comment (lamaks) [inline packages/web-api-scan-runner/src/runner/runner.ts]: we may need to keep the following to reset data in a storage:
`      originPageScanResult.scanResult = null;	
        originPageScanResult.reports = null;`
