### PR TITLE
fix href and hide it in rest response

### LINKED ISSUE #318: [Bug] GET scan result HTTP response payload should have correct report href link
The href link should be fully qualified URL that match to the GET scan report REST API including the corresponding API version:

/scans/{scanid}//reports/{reportid}?api-version=1.0

### PR DESCRIPTION
**Pull request by haonliu**
#### Description of changes

(Give an overview. Add a technical description describing your changes.)

#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #318
- [ ] Added relevant unit test for your changes. (`yarn test`)
- [ ] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [ ] Ran precheckin (`yarn precheckin`)

### CODE REVIEW

File: packages/web-api-scan-runner/src/runner/runner.ts [hunk 1]
```diff
@@ -140,7 +140,7 @@ export class Runner {
         this.logger.logInfo(`Saving sarif results to Blobs...`);
         await this.pageScanRunReportService.saveSarifReport(reportId, JSON.stringify(sarifResults));
 
-        href = this.pageScanRunReportService.getBlobFilePath(reportId, format);
+        href = this.pageScanRunReportService.getBlobFilePath(reportId, `${reportId}.${format}`);
```
Comment (devaradhanm) [inline packages/web-api-scan-runner/src/runner/runner.ts]: this bug is about fixing the blob path in cosmos storage. currently it is being stored like this:
 "reports": [
        {
            "format": "sarif",
            "href": **"2019/9/20/23/sarif",**
            "reportId": "1e9dc004-5c80-6d40-f3c2-87730f63e0ae"
        }
    ],
