### PR TITLE
fix: show incomplete e2e test suite

### LINKED ISSUE #489: [Bug] E2E tests results are missing when health monitoring orchestration reports unavailability
When health monitoring orchestration reports unavailability E2E tests must provide results to easy diagnosis the service failure point. This bug renders out all benefit of running e2e in production.

Screen Shot 2020-01-24 at 12 08 10 PM

### PR DESCRIPTION
**Pull request by pownkel**
#### Description of changes

Currently, the dashboard shows test results only for a complete run of the test suite. This means that if the E2E orchestration breaks before all tests can run, we will not be able to see updated results of the failed partial run.

With this PR, the E2E Test Results tile will still show the latest full run for the most recent releaseId, if one is available. Otherwise, it will display the available test results, as well as the names of any incomplete TestContainers with a status of "incomplete."

Here's a comparison of the old and new queries, shortly after deployment and before the full test suite completed for the new version. Note that the new query shows results for the most recent releaseId, while the old one is still showing stale results for the previous releaseId:

comparison of old and new e2e test result tiles

And the new log query in a more readable form than the dashboard template (with newlines and comments for readability):

```
// Filter for relevant events so we don't need to keep repeating this query
let functionalTestEvents = customEvents
| where name == "FunctionalTest";

let lastCompletedRun = functionalTestEvents
| where customDimensions.testContainer == "FinalizerTestGroup"
| top 1 by timestamp desc nulls last
| project runId = customDimensions.runId, releaseId = tostring(customDimensions.releaseId), key=1;

let lastStartedRun = functionalTestEvents
| top 1 by timestamp desc nulls last
| project runId = customDimensions.runId, releaseId = tostring(customDimensions.releaseId), key=1;

// Choose between the runId for the last complete test suite run, and the
// most recently started run, depending on whether they have the same releaseId
let runId = toscalar(lastCompletedRun
| join kind=fullouter lastStartedRun on key
| project value = tostring(iff(isnotnull(releaseId) and releaseId == releaseId1, runId, runId1)));

let relevantTestEvents = functionalTestEvents
| where customDimensions.runId == runId;

let completeTestRuns = relevantTestEvents
| where customDimensions.logSource == "TestRun"
| project testContainerName = tostring(customDimensions.testContainer), testName = tostring(customDimensions.testName), result = tostring(customDimensions.result), releaseId = customDimensions.releaseId, timestamp;

let completeTestContainers = relevantTestEvents
| where customDimensions.logSource == "TestContainer"
| project testContainerName = tostring(customDimensions.testContainer);

// Get the names of all TestContainers that we should be running
let testContainerNames = functionalTestEvents
| where customDimensions.source == "BeginTestSuite"
| top 1 by timestamp
| project testContainerName = split(tostring(customDimensions.functionalTestGroups), ",")
| mv-expand testContainerName
| project testContainerName = tostring(testContainerName);

// remove rows of testContainerNames that we have complete results for,
// add "incomplete" status, and concat this to the complete test runs
testContainerNames
| project testContainerName, testName = "Additional tests", result = "incomplete"
| join kind=leftanti completeTestContainers on testContainerName
| union completeTestRuns
| where testContainerName != "FinalizerTestGroup"
| sort by testContainerName

```

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #489
- [x] Added relevant unit test for your changes. (`yarn test`)
- [x] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [x] Ran precheckin (`yarn precheckin`)

### CODE REVIEW

**Comment by devaradhanm** [comment]
@pownkel , wouldnt this make it harder to look at the latest run if it is in progress? The user might have to wait & look at the dashboard only between a new e2e test run that happens in next 5-10 min & then after the current e2e test run completes. correct?

**Comment by pownkel** [comment]
@devaradhanm If there is a complete test suite run from the most recent release it will show that. It will only show incomplete results if there isn't a complete run available.

File: packages/web-workers/src/orchestration-steps.ts [hunk 1]
```diff
@@ -185,6 +187,17 @@ export class OrchestrationStepsImpl implements OrchestrationSteps {
         this.logOrchestrationStep(`Completed functional tests: ${testGroupNames}`);
     }
 
+    public logTestRunStart(getTestGroupNamesFunc: () => string[] = getAllTestGroupClassNames): void {
+        const testGroupNamesStr = getTestGroupNamesFunc().reduce((prevValue, currentValue) => `${prevValue},${currentValue}`);
```
Comment (devaradhanm) [inline packages/web-workers/src/orchestration-steps.ts]: you could use .join(',') instead of reduce. to make it more readable

File: packages/web-workers/src/orchestration-steps.ts [hunk 2]
```diff
@@ -185,6 +187,17 @@ export class OrchestrationStepsImpl implements OrchestrationSteps {
...
+        const properties = {
+            ...this.getDefaultLogProperties(),
+            functionalTestGroups: testGroupNamesStr,
+            runId: this.context.df.instanceId,
+            environment: this.availabilityTestConfig.environmentDefinition,
+        };
+        this.logger.log('Starting functional test orchestration.', LogLevel.info, properties);
```
Comment (devaradhanm) [inline packages/web-workers/src/orchestration-steps.ts]: you could use events instead of logs for this. logs are for diagnostics purposes.

File: packages/resource-deployment/templates/dashboard.template.json [hunk 3]
```diff
@@ -1035,7 +1035,7 @@
...
...vantTestEvents = functionalTestEvents\r\n| where customDimensions.runId == runId;\r\nlet completeTestRuns = relevantTestEvents\r\n| where customDimensions.logSource == \"TestRun\"\r\n| project testContainerName = tostring(customDimensions.testContainer), testName = tostring(customDimensions.testName), result = tostring(customDimensions.result), releaseId = customDimensions.releaseId, timestamp;\r\nlet completeTestContainers = relevantTestEvents\r\n| where customDimensions.logSource == \"TestContainer\"\r\n| project testContainerName = tostring(customDimensions.testContainer);\r\nlet testContainerNames = functionalTestEvents\r\n| where customDimensions.source == \"BeginTestSuite\"\r\n| top 1 by timestamp\r\n| project testContainerName = split(tostring(customDimensions.functionalTestGroups), \",\")\r\n| mv-expand testContainerName\r\n| project testContainerName = tostring(testContainerName);\r\ntestContainerNames\r\n| project testContainerName, testName = \"Additional tests\", result = \"incomplete\"\r\n| join kind=leftanti completeTestContainers on testContainerName\r\n| union completeTestRuns\r\n| where testContainerName != \"FinalizerTestGroup\"\r\n| sort by testContainerName\r\n"
```
Comment (lamaks) [inline packages/resource-deployment/templates/dashboard.template.json]: if we merge on container then we cannot see a test failing name but a fixed message `Additional tests` only. Is there a way to see test that is actually failing?

Comment (pownkel) [reply packages/resource-deployment/templates/dashboard.template.json]: We'll see the pass/fail results for individual tests, plus incomplete "additional tests" if the whole test container hasn't yet finished.

Comment (lamaks) [reply packages/resource-deployment/templates/dashboard.template.json]: Can you please post some screenshots with example. The above should have both group/test failures listed but only group is marked as failed

**Comment by pownkel** [comment]
An example screenshot with forced failures and incomplete status:

e2e dashboard with failures

File: packages/resource-deployment/templates/dashboard.template.json (hunk 3 above)
Comment (pownkel) [reply packages/resource-deployment/templates/dashboard.template.json]: Posted a screenshot below
