### PR TITLE
remove legacy error handling

### LINKED ISSUE #421: [Bug] Delete Legacy scan error handling ( string parsing in ScanRunErrorConverter)
## Describe the bug

This has to be done after a month. (after Jan 1) so that all the old documents that has scanError as string would have been deleted.

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service

### PR DESCRIPTION
**Pull request by haonliu**
#### Description of changes

remove legacy error handling

#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #421
- [ ] Added relevant unit test for your changes. (`yarn test`)
- [ ] Verified code coverage for the changes made. Check coverage report at: `<rootDir>/test-results/unit/coverage`
- [ ] Ran precheckin (`yarn precheckin`)

### CODE REVIEW

File: packages/web-api/src/converters/scan-run-error-converter.ts [hunk 1]
```diff
@@ -12,49 +12,6 @@ export class ScanRunErrorConverter {
...
-        return ScanRunErrorCodes.internalError;
-    }
-
-    private createHTTPResponseError(scanError: string): ScanRunErrorCode {
-        const errorMessage: string = scanError.slice(scanError.lastIndexOf(':') + 2);
-        const errorCode: ScanRunErrorCode = { ...ScanRunErrorCodes.httpErrorCode };
-        errorCode.message += `: ${errorMessage}`;
-
-        return errorCode;
+        return scanErrorNameToErrorMap[(<ScanError>scanError).errorType];
```
Comment (devaradhanm) [inline packages/web-api/src/converters/scan-run-error-converter.ts]: getScanRunErrorCode should only get type ScanError after this change
